export default {
  thin: 'Poppins-Thin',
  thin_italic: 'Poppins-ThinItalic',
  extraLight: 'Poppins-ExtraLight',
  extraLight_italic: 'Poppins-ExtraLightItalic',
  light: 'Poppins-Light',
  light_italic: 'Poppins-LightItalic',
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  medium_italic: 'Poppins-MediumItalic ',
  semiBold: 'Poppins-SemiBold',
  semiBold_italic: 'Poppins-SemiBoldItalic',
  bold: 'Poppins-Bold',
  bold_italic: 'Poppins-BlackItalic',
  extraBold: 'Poppins-ExtraBold',
  extraBold_italic: 'Poppins-ExtraBoldItalic',
  black: 'Poppins-Black',
  black_italic: 'Poppins-BlackItalic',
};
