export default {
  thin: 'Inter-Thin',
  thin_italic: 'Inter-ThinItalic',
  extraLight: 'Inter-ExtraLight',
  extraLight_italic: 'Inter-ExtraLightItalic',
  light: 'Inter-Light',
  light_italic: 'Inter-LightItalic',
  regular: 'Inter-Regular',
  italic: 'Inter-Italic',
  medium: 'Inter-Medium',
  medium_italic: 'Inter-MediumItalic',
  semiBold: 'Inter-SemiBold',
  semiBold_italic: 'Inter-SemiBoldItalic',
  bold: 'Inter-Bold',
  bold_italic: 'Inter-BoldItalic',
  extraBold: 'Inter-ExtraBold',
  extraBold_italic: 'Inter-ExtraBoldItalic',
  black: 'Inter-Black',
  black_italic: 'Inter-BlackItalic',
};
