export const Icons = {
  Whatsapp: require('./whatsapp.png'),
  MyOrders: require('./myOrders.png'),
  MyPayments: require('./myPayments.png'),
  MySavings: require('./mySavings.png'),
  MyWishlist: require('./wishlist.png'),
  MyOrdersFull: require('./myOrdersFull.png'),
  MySavingsFull: require('./mySavingsFull.png'),
  MyPaymentsFull: require('./myPaymentsFull.png'),
  Dashboard: require('./dashboard.png'),
  Faq: require('./faq.png'),
  DeleteAccount: require('./delete-account.png'),
  MyEstablishment: require('./my-establishment.png'),
  SelectLanguage: require('./select-language.png'),
  Invite: require('./invite.png'),
  Gpay: require('./gpay.png'),
  Upi: require('./upi.png'),
  SBI: require('./sbi.png'),
  Kotak: require('./kotak.png'),
  MasterCard: require('./master.png'),
  Visa: require('./visa.png'),

  WishlistIcon: require('./saved.png'),
  ManageCertificates: require('./manage-certificates.png'),
  SavedDrafts: require('./saved-drafts.png'),
  MyPosts: require('./my-posts.png'),
  Success: require('./success.png'),
  postInsight: require('./postInsight.jpg'),
  Inventory: require('./Inventory.jpg'),
  Collections: require('./Collections.jpg'),
  lockIcon: require("./lock.png"),
  appLogo: require("./logo.png"),
  smsIcon: require("./sms.png"),
  eyeOpenIcon: require("./eye-open.png"),
  eyeCloseIcon: require("./eye-closed.png"),
  userIcon: require("./user.png"),
  googleIcon: require("./ic_google.png")
};
