version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://raushanrkp1:8tmvJiljLIOk3bv6@cluster0.xgwvf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
