version: '3.4'

services:
  be:
    image: be
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5001:5001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/server.js"]
